src/Entity/Heros.php
<?php

namespace App\Entity;

use App\Repository\HerosRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\ClassHeros;

#[ORM\Entity(repositoryClass: HerosRepository::class)]
class Heros
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $birth_date = null;

    #[ORM\Column]
    private ?int $level = null;

    #[ORM\Column]
    private ?int $experience = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $healt_point = null;

    #[ORM\ManyToOne(inversedBy: 'heros')]
    // #[ORM\JoinColumn(nullable: false)]
    private ?ClassHeros $classHeros = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(int $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getExperience(): ?int
    {
        return $this->experience;
    }

    public function setExperience(int $experience): self
    {
        $this->experience = $experience;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getHealtPoint(): ?int
    {
        return $this->healt_point;
    }

    public function setHealtPoint(int $healt_point): self
    {
        $this->healt_point = $healt_point;

        return $this;
    }

    public function getClassHeros(): ?ClassHeros
    {
        return $this->classHeros;
    }

    public function setClassHeros(?ClassHeros $classHeros): self
    {
        $this->classHeros = $classHeros;

        return $this;
    }
}

src/Controller/HeroController.php
<?php

namespace App\Controller;


use App\Entity\Heros;
use App\Repository\HerosRepository;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Doctrine\Persistence\ManagerRegistry;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HeroController extends AbstractController
{
    /**
     * Homepage du site, rien de particulier
     */
    #[Route('/', name: 'home')]
    public function index(): Response
    {
        return $this->render('homepage.html.twig',);
    }

    #[Route('/character', name: 'show_character')]
    public function show(HerosRepository $repository): Response
    {
        $allHeroes = $repository->findAll();
        return $this->render('hero/index.html.twig', [
            'heroes' => $allHeroes,
        ]);
    }

    /**
     * Fonction d'ajout et d'édition de héros, le formulaire est fait main
     */
    #[Route('/character/add', name: 'add_character')]
    #[Route('/character/edit/{id}', name: 'edit_character')]
    public function form(Heros $hero = null, Request $request, ManagerRegistry $manager)
    {
        if (!$hero) {
            $hero = new Heros();
        }

        $form = $this->createFormBuilder($hero)
            ->add('name')
            ->add('birthdate', DateTimeType::class, [
                'date_label' => 'Starts on'
            ])
            ->add('classHeros')
            // ->add('skillName')
            ->add('description')
            ->add('level')
            ->add('experience')
            ->add('healtpoint')
            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $manager->getManager();
            $em->persist($hero);
            $em->flush();

            return $this->redirectToRoute('show_character', ['id' => $hero->getId()]);
        }

        return $this->render('hero/create.html.twig', [
            'formHero' => $form->createView(),
            'editMode' => $hero->getId() !== null
        ]);
    }

    /**
     * Fonction de supression d'un héros
     */
    #[Route('/character/delete/{id}', name: 'delete_character')]
    public function delete(Heros $hero, ManagerRegistry $manager): RedirectResponse
    {
        $em = $manager->getManager();
        $em->remove($hero);
        $em->flush();

        return $this->redirectToRoute(route: "home");
    }
}

templates/hero/create.html.twig
{% extends 'homepage.html.twig' %}

{% form_theme formHero 'bootstrap_4_layout.html.twig' %}

{% block title %}Creation d'un heros
{% endblock %}

{% block body %}

	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}
	</style>

	<div class="example-wrapper">
		<h1>Création d'un héros</h1>

		{{ form_start(formHero) }}

		{{ form_widget(formHero) }}

		<button type="submit" class="btn btn-success">
			{% if editMode %}
				Enregistrer les modifications
			{% else %}
				Créer le héros
			{% endif %}
		</button>

		{{ form_end(formHero) }}
	</div>
{% endblock %}

templates/hero/index.html.twig
{% extends 'homepage.html.twig' %}

{% block title %}Liste des héros{% endblock %}

{% block body %}
    <div class="album py-5 bg-light"
        <div class="container-fluid">
            <div class="row">
            {% for hero in heroes %}        
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <div class="card-body">
                            <h5 class="card-title">{{ hero.name }}</h5>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-items">Description : {{ hero.description }}</li>
                            <li class="list-group-items">Classe : {{ hero.classHeros }}</li>
                            <li class="list-group-items">Création : {{ hero.birthDate | date('d/m/y') }}</li>
                            <li class="list-group-items">Niveau : {{ hero.level }}</li>
                            <li class="list-group-items">Expérience : {{ hero.experience }}</li>
                            <li class="list-group-items">Point de vie : {{ hero.healtpoint }}</li>
                            
                        </ul>
                            <div class="card-body">
                                <div class="btn-group">
                                    <a href="{{ path('edit_character', {"id": hero.id}) }}" class="btn btn-sm btn-outline-secondary">Editer</a>
                                    <a href="{{ path('delete_character', {"id": hero.id}) }}" class="btn btn-sm btn-outline-secondary" onclick="return confirm('Confirmez la suppression')">Supprimer</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>


{% endblock %}